### ISSUE TITLE
Sandbox issue

### ISSUE THREAD

**Issue by alphamg2003** [alphamg2003/osu-mg-reload#5]
Will only use this to experience GitHub's features

**Comment by alphamg2003** [comment]
- [ ] https://github.com/alphamg2003/osu-mg-reload/issues/1
- [ ] https://github.com/alphamg2003/osu-mg-reload/issues/2
- [ ] https://github.com/alphamg2003/osu-mg-reload/issues/3
- [x] https://github.com/alphamg2003/osu-mg-reload/issues/4

**Comment by alphamg2003** [comment]
O, I see

**Comment by alphamg2003** [comment]
Mmmm, Lock comment feature

**Comment by alphamg2003** [comment]
Test

**Comment by greenmg2003** [comment]
Yo... Wick

**Comment by greenmg2003** [comment]
I guess this should be it

**Comment by greenmg2003** [comment]
Setting up the Webhook all again is pain...

**Comment by greenmg2003** [comment]
Dang it, Wick, you broke the perfect setup for GitHub Webhook...
